
function MakeId(s) {
    if (s) {
        oid = ObjectId(s)
    } else {
        oid = ObjectId()
    }
    r = HexData(0,oid.str).base64().replace(/\+/g, '-').replace(/\//g, '_')
    print("Creating " + r)
    return r
}


conn = new Mongo();
db = conn.getDB("ctp");

db.dropDatabase()

db = conn.getDB("ctp");

/*********************/
x = {
    "_id": "0",
    "name": "ctp prototype server",
    "annotation": "This ctp server exposes mock data for demonstration purposes only. Data was generated by the build_db.js script.",
    "provider": "csa.demo",
    "version": "0",
}
db.baseuri.insert(x)

/*********************/
access_id = MakeId()
access_id_tag = "account:" + access_id

x = {
    "_id": access_id,
    "accessTags": [ "role:admin" ],
    "name": "ordinary user",
    "accountTags": [ access_id_tag, "role:user" ],
    "token": "1234",
}

db.accounts.insert(x);

x = {
    "_id": MakeId(),
    "accessTags": [ "role:admin" ],
    "name": "super user",
    "accountTags": [ "*" ],
    "token": "0000",
}

db.accounts.insert(x);

/*********************/
serviceViewId = MakeId("548610513d561badbc7e16d0")

x = {
    "_id": serviceViewId, 
    /* no parent */
    "accessTags": [ access_id_tag ],
    "name": "compute service provider",
    "annotation": "mock data",
    "provider": "csa.demo"
}

db.serviceViews.insert(x);

/*********************/
/* TODO: We should probably index on "key" in real life in the "tokens" collection */


/**********************/

assetId = MakeId("548610513d561badbc7e16d4")

x = {
    "_id": assetId,
    "parent": [ serviceViewId ],
    "accessTags": [ access_id_tag ],
    "name": "Webserver on machine 1",
    "annotation": "Webserver running on Linux Ubuntu (apache)",
    "name": "https://paris.matrix.lan/"
}

db.assets.insert(x);

/**********************/

attributeId = MakeId("548610513d561badbc7e16d5")

x = { 
    "_id": attributeId,
    "parent": [ assetId, serviceViewId ],
    "accessTags": [ access_id_tag ],
    "annotation": "Availability attribute for demo",
    "name": "availability"
}

db.attributes.insert(x);

/**********************/

metricId = MakeId("548610513d561badbc7e16d6")

x = {
    "_id" : metricId,
    /* no parent */
    "accessTags": [ "role:user" ],
    "name": "unix uptime",
    "annotation" : "",
    "baseMetric" : "https://cloudsecurityalliance.org/ctp/metrics#csa:unix-uptime",
    "measurementParameters" : [ ],
    "resultFormat" : [
    { 
        "name": "1-minute-load-average", 
        "type": "number" 
    },
    { 
        "name": "5-minute-load-average", 
        "type": "number" 
    },
    { 
        "name": "15-minute-load-average", 
        "type": "number" 
    }
    ],
}

db.metrics.insert(x)

/**********************/


measurementId = MakeId("548610513d561badbc7e1600")

x = {
    "_id" : measurementId,
    "parent" : [ attributeId, assetId, serviceViewId ], 
    "accessTags": [ access_id_tag ],
    "name": "unix uptime",
    "annotation" : "",
    "metric" : "@/metrics/" + metricId,
    "result" : {
        "value" : [
            { 
                "1-minute-load-average": 1.5,
                "5-minute-load-average": 1.7841, 
                "15-minute-load-average": 0.89 
            }
        ],
        "dateTime" : ISODate()
    },
    "objective" : {
        "condition" : "value[0]['1-minute-load-average']<5",
        "status" : true
    },
    "userActivated": false,
    "state" : "activated"
}

db.measurements.insert(x);

/**********************/
/** PART II ***********/
/**********************/

attributeId = MakeId()

x = { 
    "_id": attributeId,
    "parent": [assetId, serviceViewId ],
    "accessTags": [ access_id_tag ],
    "annotation": "confidentiality of data in transit with SSL/TLS",
    "name": "confidentiality"
}

db.attributes.insert(x);

/**********************/

metricId = MakeId()

x = {
        "_id" : metricId,
        "accessTags": [ access_id_tag ],
        "name": "encryption strength",
        "annotation" : "",
        "baseMetric" : "https://cloudsecurityalliance.org/ctp/metrics#csa:cryptographic-strength",
        "measurementParameters" : [ 
                {
                    "name": "scale",
                    "type": "string",
                    "value": "ECRYPT II"
                }
            ],
        "resultFormat" : [
            { 
                "name": "level", 
                "type": "number" 
            },
        ],
}

db.metrics.insert(x);

/**********************/

measurementId = MakeId()

    x = {
        "_id" : measurementId,
        "parent" : [ attributeId, assetId, serviceViewId ],
        "accessTags": [ access_id_tag ],
        "name": "SSL/TLS encryption strength",
        "annotation" : "",
        "metric" : "@/metrics/" + metricId,
        //"metric" : metricId,
        "result" : {
            "value" : [
                { 
                    "level": 7,
                }
            ],
            "dateTime" : ISODate()
        },       
        "objective" : {
            "condition" : "value[0].level>=7",
            "status" : true
        },
        "userInitiated" : "false",
        "state" : "activated"

}


db.measurements.insert(x);

/*****************/

print("Dummy schema loaded: OK.")
